version: "3.1"
networks:
  mongo:
services:
  mongo:
    container_name: mongo-clean-ts
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: teste
      MONGO_INITDB_ROOT_PASSWORD: teste
    volumes:
      - ./data-db:/data/db
    ports:
      - "22222:27017"
    networks:
      - mongo
  api:
    container_name: api-clean-ts
    build: .
    image: clean-node-api
    command: npm run debug
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    networks:
      - mongo
